### ISSUE TITLE
[Feature Request] Scale with resolution

### ISSUE THREAD

**Issue by matyX6** [lukakldiashvili/Unified-Universal-Blur#13] opened 2024-03-22 09:44 UTC
When I change the resolution, on lower resolutions it seems like there are more blur. I tried to implement "resolution scaling" solution for my post processing effects as well as for this asset, to have more consistent results across multiple resolutions. The change in blur visuals is very noticable when going from desktop pc (high resolution 1440p) to Steam Deck (lower resolution 800p).

I included reference photo in which it is clearly visible that the blur is not consistent on multiple resolutions without scaling, I included my solution photo as well. Could you add this feature, I'd like to use it as a package instead with your own edits?

Is this the "safe" approach, or any other way to scale blur with resolution?

![scaling-blur](https://github.com/lukakldiashvili/Unified-Universal-Blur/assets/38249194/128cb639-d48d-42a6-82e5-aac9ade3396c)

My edits and solution:
![scaling-feature-edits](https://github.com/lukakldiashvili/Unified-Universal-Blur/assets/38249194/993aea1d-73b7-4729-b866-d694e077beb7)
![scaling-pass-edits](https://github.com/lukakldiashvili/Unified-Universal-Blur/assets/38249194/627fc925-a27f-47c1-87b1-b2e62133bf8a)

**Comment by matyX6** [comment] 2024-03-22 10:48
One other thing that crosses my mind is maybe to incorporate URP render scaling as well since it also affects blur... And will be useful for everybody that changes it from a default value.

So in the end code could look something like:
var urpAsset = (UniversalRenderPipelineAsset)GraphicsSettings.renderPipelineAsset;
scale *= (Screen.height * urpAsset.renderScale) / passData.referenceResolutionHeight

**Comment by lukakldiashvili** [comment] 2024-03-25 21:23
Hi @matyX6, thank you for the request and the solution. I'll make sure to implement this feature, soon.

**Comment by lukakldiashvili** [comment] 2024-05-19 12:16
Sorry for the delay. After testing in the editor, default behaviour produced better/correct results compared to this request.
I may implement this kind of scaling as an optional feature later down in line.

In the meantime, please check if some other changes are affecting the scaling.

**Comment by lukakldiashvili** [comment] 2024-05-19 12:31
After further investigation, this seems to be caused by difference between behaviours of RenderingUtils.ReAllocateIfNeeded and RenderTexture constructor, where only latter one working as intended. This solution is needed for editor versions `UNITY_2022_1_OR_NEWER`.

Solution will be released in the next version, probably in a different way. Thank you for raising the issue.

**Closed by lukakldiashvili** 2024-05-19 12:31 UTC
